[tool.poetry]
name = "cnsplots"
version = "0.0.1"
description = ""
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
matplotlib = "*"
seaborn = "*"
scanpy = "*"
lifelines = "*"
pydeseq2 = "*"
upsetplot = "*"
adjustText = "*"
matplotlib-venn = "*"
pycomplexheatmap = "*"
palettable = "*"
numpy = "*"
pandas = "*"
scipy = "*"
natsort = "*"
num2tex = "*"
scikit-learn = "*"
statannotations = { git = "https://github.com/trevismd/statannotations", branch = "master" }

[tool.poetry.group.dev.dependencies]
pre-commit = "*"

[tool.poetry.group.doc.dependencies]
sphinx = "*"
furo = "*"
sphinx-gallery = "*"
sphinx_design = "*"
sphinx-copybutton = "*"
sphinx-hoverxref = "*"
sphinx-autodoc-typehints = "*"
myst-parser = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
