[project]
name = "cnsplots"
version = "0.0.1"
description = ""
requires-python = ">=3.8,<4.0"
dependencies = [
    "matplotlib",
    "seaborn",
    "scanpy",
    "lifelines",
    "pydeseq2",
    "upsetplot",
    "adjustText",
    "matplotlib-venn",
    "pycomplexheatmap",
    "palettable",
    "numpy",
    "pandas",
    "scipy",
    "natsort",
    "num2tex",
    "scikit-learn",
    "statannotations @ git+https://github.com/trevismd/statannotations@master",
]

[project.optional-dependencies]
doc = [
    "sphinx",
    "furo",
    "sphinx-gallery",
    "sphinx_design",
    "sphinx-copybutton",
    "sphinx-hoverxref",
    "sphinx-autodoc-typehints",
    "myst-parser",
]
dev = [
    "pre-commit",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["cnsplots"]
