[project]
name = "cnsplots"
version = "0.0.1"
description = ""
requires-python = ">=3.8,<4.0"
dependencies = [
    "adjustText",
    "lifelines",
    "lxml",
    "matplotlib",
    "matplotlib-venn",
    "natsort",
    "num2tex",
    "numpy",
    "palettable",
    "pandas",
    "pycomplexheatmap",
    "scanpy",
    "scikit-learn",
    "scipy",
    "seaborn",
    "upsetplot",
    "gseapy",
    "statsmodels ; python_version >= '3.9' and python_version < '4.0'",
    "statannotations @ git+https://github.com/trevismd/statannotations@master",
]

[project.optional-dependencies]
doc = [
    "sphinx",
    "furo",
    "myst-parser",
    "sphinx-autodoc-typehints",
    "sphinx-copybutton",
    "sphinx-gallery",
    "sphinx-hoverxref",
    "sphinx_design",
]
dev = ["pre-commit", "cmprsk"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["cnsplots"]

[tool.ruff]
target-version = "py38"

[tool.ruff.format]
docstring-code-format = true
