"""CNSPlots Module."""

import warnings

from cnsplots._plots import (
    barplot,
    boxplot,
    confusionplot,
    cumulativeincidenceplot,
    distplot,
    donutplot,
    dotplot,
    forestplot,
    heatmapplot,
    histplot,
    kdeplot,
    lineplot,
    phyloplot,
    pieplot,
    qqplot,
    regplot,
    ridgeplot,
    sankeyplot,
    scatterplot,
    slopeplot,
    stackplot,
    stripplot,
    survivalplot,
    upsetplot,
    vennplot,
    violinplot,
    volcanoplot,
)
from cnsplots._setup import setup_matplotlib
from cnsplots._utils import (
    BLUE,
    BROWN,
    GRAY,
    GREEN,
    ORANGE,
    PINK,
    PURPLE,
    RED,
    YELLOW,
    figure,
    get_hexcolors_from_apalette,
    palettes,
    take_legend_out,
)

__version__ = "0.0.1"
__all__ = (
    setup_matplotlib,
    figure,
    palettes,
    take_legend_out,
    get_hexcolors_from_apalette,
    barplot,
    boxplot,
    confusionplot,
    cumulativeincidenceplot,
    distplot,
    donutplot,
    dotplot,
    forestplot,
    heatmapplot,
    histplot,
    kdeplot,
    lineplot,
    phyloplot,
    pieplot,
    qqplot,
    regplot,
    ridgeplot,
    sankeyplot,
    scatterplot,
    slopeplot,
    stackplot,
    stripplot,
    survivalplot,
    upsetplot,
    vennplot,
    violinplot,
    volcanoplot,
)

warnings.filterwarnings("ignore", message="findfont:", module="cnsplots.*")
