"""CNSPlots Module."""

from cnsplots._plots import (
    barplot,
    boxplot,
    confusionplot,
    distplot,
    donutplot,
    hazardplot,
    heatmapplot,
    histplot,
    kdeplot,
    lineplot,
    phyloplot,
    pieplot,
    regplot,
    ridgeplot,
    sankeyplot,
    scatterplot,
    slopeplot,
    stackplot,
    stripplot,
    survivalplot,
    upsetplot,
    vennplot,
    violinplot,
    volcanoplot,
)
from cnsplots._setup import setup_matplotlib
from cnsplots._utils import (
    figure,
    get_specific_hex_colors_from_set1,
    palettes,
    take_legend_out,
)

__version__ = "0.0.1"
__all__ = (
    setup_matplotlib,
    figure,
    palettes,
    take_legend_out,
    get_specific_hex_colors_from_set1,
    barplot,
    boxplot,
    confusionplot,
    distplot,
    donutplot,
    hazardplot,
    heatmapplot,
    histplot,
    kdeplot,
    lineplot,
    phyloplot,
    pieplot,
    regplot,
    ridgeplot,
    sankeyplot,
    scatterplot,
    slopeplot,
    stackplot,
    stripplot,
    survivalplot,
    upsetplot,
    vennplot,
    violinplot,
    volcanoplot,
)
